[tool.poetry]
name = "mimo-practice"
version = "0.1.0"
description = ""
authors = ["MichaelSpicer1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aflr = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
